"""Unit tests for lightweight 3D reconstruction helpers."""

from __future__ import annotations

import json

import numpy as np
import pytest

from backend.services.reconstruction import (
    build_preview_points,
    depth_to_point_cloud,
    normalize_reconstruction_format,
    serialize_obj,
    serialize_ply,
)


def _synthetic_image(width: int = 4, height: int = 3) -> np.ndarray:
    img = np.zeros((height, width, 3), dtype=np.uint8)
    img[..., 0] = 10  # B
    img[..., 1] = np.arange(height, dtype=np.uint8)[:, None] * 20  # G
    img[..., 2] = np.arange(width, dtype=np.uint8)[None, :] * 30  # R
    return img


def _synthetic_depth(width: int = 4, height: int = 3) -> np.ndarray:
    return np.linspace(0.0, 1.0, num=width * height, dtype=np.float32).reshape(height, width)


def test_depth_to_point_cloud_shape_metadata_and_rgb_conversion() -> None:
    cloud = depth_to_point_cloud(
        _synthetic_image(),
        _synthetic_depth(),
        depth_near_percentile=0.0,
        depth_far_percentile=100.0,
        coordinate_system="camera",
    )

    points = cloud["points"]
    colors = cloud["colors"]
    metadata = cloud["metadata"]

    assert points.shape == (12, 3)
    assert points.dtype == np.float32
    assert colors.shape == (12, 3)
    assert colors.dtype == np.uint8
    assert colors[0].tolist() == [0, 0, 10]
    assert metadata["point_count"] == 12
    assert metadata["source_width"] == 4
    assert metadata["source_height"] == 3
    assert metadata["focal_px"] == pytest.approx(4.8)
    assert metadata["bounds"]["min"][2] == pytest.approx(0.0)
    assert metadata["bounds"]["max"][2] == pytest.approx(1.0)


def test_y_up_coordinate_system_flips_y_sign() -> None:
    img = _synthetic_image()
    depth = _synthetic_depth()
    camera = depth_to_point_cloud(
        img,
        depth,
        coordinate_system="camera",
        depth_near_percentile=0.0,
        depth_far_percentile=100.0,
    )["points"]
    y_up = depth_to_point_cloud(
        img,
        depth,
        coordinate_system="y_up",
        depth_near_percentile=0.0,
        depth_far_percentile=100.0,
    )["points"]

    np.testing.assert_allclose(y_up[:, 0], camera[:, 0])
    np.testing.assert_allclose(y_up[:, 1], -camera[:, 1])
    np.testing.assert_allclose(y_up[:, 2], camera[:, 2])


def test_max_points_limits_output_count() -> None:
    cloud = depth_to_point_cloud(
        _synthetic_image(width=80, height=80),
        _synthetic_depth(width=80, height=80),
        max_points=1000,
    )

    assert cloud["points"].shape[0] == 1000
    assert cloud["metadata"]["point_count"] == 1000


def test_grid_sampling_is_deterministic() -> None:
    img = _synthetic_image(width=60, height=60)
    depth = _synthetic_depth(width=60, height=60)

    first = depth_to_point_cloud(img, depth, max_points=1000, sampling="grid")["points"]
    second = depth_to_point_cloud(img, depth, max_points=1000, sampling="grid")["points"]

    np.testing.assert_array_equal(first, second)


def test_random_sampling_is_deterministic_with_fixed_seed() -> None:
    img = _synthetic_image(width=60, height=60)
    depth = _synthetic_depth(width=60, height=60)

    first = depth_to_point_cloud(img, depth, max_points=1000, sampling="random")["points"]
    second = depth_to_point_cloud(img, depth, max_points=1000, sampling="random")["points"]

    np.testing.assert_array_equal(first, second)


def test_degenerate_depth_raises_clean_value_error() -> None:
    with pytest.raises(ValueError, match="degenerate range"):
        depth_to_point_cloud(_synthetic_image(), np.ones((3, 4), dtype=np.float32))


def test_serialize_ply_header_and_vertex_count() -> None:
    points = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float32)
    colors = np.array([[255, 0, 128], [1, 2, 3]], dtype=np.uint8)

    text = serialize_ply(points, colors).decode("utf-8")

    assert text.startswith("ply\nformat ascii 1.0\nelement vertex 2")
    assert "property uchar red" in text
    assert "end_header\n1.000000 2.000000 3.000000 255 0 128" in text
    assert len([line for line in text.splitlines() if line and line[0].isdigit()]) == 2


def test_serialize_obj_writes_vertex_color_floats() -> None:
    points = np.array([[1.0, 2.0, 3.0]], dtype=np.float32)
    colors = np.array([[255, 128, 0]], dtype=np.uint8)

    text = serialize_obj(points, colors).decode("utf-8")

    assert text.startswith("# generated by DepthLens Pro\n# point count: 1")
    assert "v 1.000000 2.000000 3.000000 1.000000 0.501961 0.000000" in text


def test_build_preview_points_respects_limit_and_is_json_safe() -> None:
    points = np.array([[float(i), float(i + 1), float(i + 2)] for i in range(10)], dtype=np.float32)
    colors = np.array([[i, i + 1, i + 2] for i in range(10)], dtype=np.uint8)

    preview = build_preview_points(points, colors, 3)

    assert len(preview) == 3
    assert preview[0] == [0.0, 1.0, 2.0, 0, 1, 2]
    json.dumps(preview)
    assert build_preview_points(points, colors, 0) == []


def test_normalize_reconstruction_format_rejects_unsupported_formats() -> None:
    assert normalize_reconstruction_format(None) == "ply"
    assert normalize_reconstruction_format("OBJ") == "obj"
    with pytest.raises(ValueError, match="export_format"):
        normalize_reconstruction_format("glb")
