const fs = require("fs");
const path = require("path");
const SETTINGS_SCHEMA_VERSION = 1;
const SETTINGS_FILE = "settings.json";
const SAFE_SETTING_KEYS = new Set(["selectedModel", "selectedDevice", "selectedColormap", "targetFps", "webcamFrameMaxDimension", "smoothingPreference", "recentBenchmarkSettings", "onnxPreference", "onnxStatus", "ui", "privacy"]);
const DEFAULT_PERSISTED_SETTINGS = { schemaVersion: SETTINGS_SCHEMA_VERSION, selectedModel: "MiDaS_small", selectedDevice: "auto", selectedColormap: "inferno", targetFps: 2, webcamFrameMaxDimension: 384, smoothingPreference: 0.25, recentBenchmarkSettings: { model: "MiDaS_small", device: "auto", iterations: 3 }, onnxPreference: "auto", onnxStatus: "unknown", ui: {}, privacy: {} };
function getSettingsPath(app) { return path.join(app.getPath("userData"), SETTINGS_FILE); }
function sanitizeSettings(input = {}) { const next = { ...DEFAULT_PERSISTED_SETTINGS, schemaVersion: SETTINGS_SCHEMA_VERSION }; if (input && typeof input === "object") { for (const [key, value] of Object.entries(input)) { if (SAFE_SETTING_KEYS.has(key)) next[key] = value; } } next.targetFps = [1, 2, 3, 5].includes(Number(next.targetFps)) ? Number(next.targetFps) : 2; next.webcamFrameMaxDimension = [256, 384, 512].includes(Number(next.webcamFrameMaxDimension)) ? Number(next.webcamFrameMaxDimension) : 384; next.smoothingPreference = Math.max(0, Math.min(0.95, Number(next.smoothingPreference) || 0)); return next; }
function readPersistedSettings(app, log = console) { const file = getSettingsPath(app); try { if (!fs.existsSync(file)) return { ...DEFAULT_PERSISTED_SETTINGS }; return sanitizeSettings(JSON.parse(fs.readFileSync(file, "utf8"))); } catch (err) { const backup = `${file}.corrupt-${Date.now()}`; try { fs.renameSync(file, backup); log.warn("SETTINGS_CORRUPT_BACKED_UP", { file, backup, error: err.message }); } catch (_) {} return { ...DEFAULT_PERSISTED_SETTINGS, recoveredFromCorruption: true }; } }
function writePersistedSettings(app, payload) { const file = getSettingsPath(app); fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 }); const clean = sanitizeSettings(payload); const tmp = `${file}.tmp-${process.pid}`; fs.writeFileSync(tmp, `${JSON.stringify(clean, null, 2)}\n`, { encoding: "utf8", mode: 0o600 }); fs.renameSync(tmp, file); try { fs.chmodSync(file, 0o600); } catch (_) {} return clean; }
module.exports = { SETTINGS_SCHEMA_VERSION, SETTINGS_FILE, SAFE_SETTING_KEYS, DEFAULT_PERSISTED_SETTINGS, getSettingsPath, sanitizeSettings, readPersistedSettings, writePersistedSettings };
