"use strict";
(function attachContracts(root) {
  function appendIfSet(form, key, value) { if (value !== undefined && value !== null && value !== "") form.append(key, value); }
  function buildEstimateRequest(o) { const form = new FormData(); form.append("file", o.file); appendIfSet(form,"model",o.model); appendIfSet(form,"colormap",o.colormap); appendIfSet(form,"device",o.device); appendIfSet(form,"metrics",o.metrics); appendIfSet(form,"outputs",o.outputs); appendIfSet(form,"max_dim",o.maxDim); if (o.gtFile) form.append("gt_file", o.gtFile); appendIfSet(form,"gt_required",o.gtRequired); appendIfSet(form,"gt_scale",o.gtScale); appendIfSet(form,"gt_invalid_value",o.gtInvalidValue); return { endpoint:"/estimate", method:"POST", body:form }; }
  function buildCompareRequest(o) { const form = new FormData(); form.append("file", o.file); appendIfSet(form,"models", Array.isArray(o.models) ? o.models.join(",") : o.models); appendIfSet(form,"device",o.device); appendIfSet(form,"colormap",o.colormap); appendIfSet(form,"metrics",o.metrics); appendIfSet(form,"outputs",o.outputs); appendIfSet(form,"max_dim",o.maxDim); appendIfSet(form,"engine",o.engine); return { endpoint:"/compare", method:"POST", body:form }; }
  function buildBenchmarkRequest(o) { const q = new URLSearchParams(); appendIfSet(q,"model",o.model); appendIfSet(q,"device",o.device); appendIfSet(q,"iterations",o.iterations); return { endpoint:`/benchmark?${q.toString()}`, method:"GET" }; }
  function buildDetectRequest(o) { const form = new FormData(); form.append(o.frame ? "frame" : "file", o.frame || o.file); appendIfSet(form,"threshold",o.threshold); appendIfSet(form,"max_detections",o.maxDetections); appendIfSet(form,"device",o.device); return { endpoint:"/detect", method:"POST", body:form }; }
  function buildReconstructRequest(o) { const form = new FormData(); form.append("file", o.file); for (const [k, v] of Object.entries({model:o.model, device:o.device, colormap:o.colormap, export_format:o.exportFormat, max_points:o.maxPoints, preview_points:o.previewPoints, focal_scale:o.focalScale, depth_scale:o.depthScale, depth_near_percentile:o.depthNearPercentile, depth_far_percentile:o.depthFarPercentile, coordinate_system:o.coordinateSystem, sampling:o.sampling, include_rgb:o.includeRgb, max_dim:o.maxDim})) appendIfSet(form,k,v); return { endpoint:"/reconstruct", method:"POST", body:form }; }
  function buildCacheClearRequest() { return { endpoint:"/cache/clear", method:"POST" }; }
  function buildObservabilityRequest() { return { endpoint:"/observability", method:"GET" }; }
  function normalizeApiError(err) { if (err instanceof Error) return { errorCode:"NETWORK_ERROR", message: err.message || "Network request failed", retryable:true }; const detail = err && err.detail !== undefined ? err.detail : err; if (detail && typeof detail === "object") return { errorCode: detail.error_code || detail.errorCode || "API_ERROR", message: detail.message || detail.error || "Request failed", retryable: detail.retryable }; if (typeof detail === "string") return { errorCode:"API_ERROR", message: detail }; return { errorCode:"API_ERROR", message:"Request failed" }; }
  function normalizeEmbeddedError(item) { return normalizeApiError(item && (item.error_detail || item.error || item)); }
  function revokeObjectUrl(url, api) { if (url && api && typeof api.revokeObjectURL === "function") api.revokeObjectURL(url); }
  function destroyChart(chart) { if (chart && typeof chart.destroy === "function") chart.destroy(); }
  function stopWebcamStream(stream) { if (stream && typeof stream.getTracks === "function") stream.getTracks().forEach((t) => t && typeof t.stop === "function" && t.stop()); }
  const api = { buildEstimateRequest, buildCompareRequest, buildBenchmarkRequest, buildDetectRequest, buildReconstructRequest, buildCacheClearRequest, buildObservabilityRequest, normalizeApiError, normalizeEmbeddedError, revokeObjectUrl, destroyChart, stopWebcamStream };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  root.DepthLensContracts = api;
})(typeof window !== "undefined" ? window : globalThis);
