"use strict";

// ══════════════════════════════════════════════════════════════
// DOM BINDINGS
// ══════════════════════════════════════════════════════════════
const $ = (s, ctx = document) => ctx.querySelector(s);
const $$ = (s, ctx = document) => [...ctx.querySelectorAll(s)];

const el = {
  welcomeScreen:   $("#welcomeScreen"),
  getStartedBtn:   $("#getStartedBtn"),
  appShell:        $("#appShell"),

  // Theme
  themeToggleLanding: $("#themeToggleLanding"),
  themeToggleHeader:  $("#themeToggleHeader"),
  themeToggleBtn:     $("#themeToggleBtn"),

  // Header
  headerNavShell:          $("#headerNavShell"),
  settingsMenuHost:        $("#settingsMenuHost"),
  settingsMenuButton:      $("#settingsMenuButton"),
  settingsPanel:           $("#settingsPanel"),
  settingsPanelClose:      $("#settingsPanelClose"),
  settingsPanelBody:       $("#settingsPanelBody"),
  engineStatusHost:        $("#engineStatusHost"),
  engineStatusButton:      $("#engineStatusButton"),
  engineStatusPanel:       $("#engineStatusPanel"),
  engineStatusClose:       $("#engineStatusClose"),
  engineStatusRefresh:     $("#engineStatusRefresh"),
  engineStatusStateValue:  $("#engineStatusStateValue"),
  engineStatusBackendUrl:  $("#engineStatusBackendUrl"),
  engineStatusReadiness:   $("#engineStatusReadinessValue"),
  engineStatusDiagnostics: $("#engineStatusDiagnosticsValue"),
  engineStatusRuntime:     $("#engineStatusRuntimeValue"),
  engineStatusCache:       $("#engineStatusCacheValue"),
  engineStatusLoadedModels:$("#engineStatusLoadedModels"),
  engineStatusSystem:      $("#engineStatusSystemValue"),
  engineStatusModules:     $("#engineStatusModules"),
  engineStatusUpdatedAt:   $("#engineStatusUpdatedAt"),

  statusDot:    $("#statusDot"),
  statusLabel:  $("#statusLabel"),
  statusSub:    $("#statusSub"),
  deviceBadge:  $("#deviceBadge"),
  navBtns:      $$(".nav-btn"),
  panels:       $$(".panel"),

  // Device
  deviceInfoBanner: $("#deviceInfoBanner"),
  deviceTypeToggle: $("#deviceTypeToggle"),
  deviceSelector:   $("#deviceSelector"),
  engineMode:       $("#engineMode"),

  // Upload queue
  dropZone:  $("#dropZone"),
  fileInput: $("#fileInput"),
  fileQueue: $("#fileQueue"),
  clearBtn:  $("#clearBtn"),
  cancelBtn: $("#cancelBtn"),
  runBtn:    $("#runBtn"),
  gtToggle: $("#gtToggle"),
  gtUpload: $("#gtUpload"),
  gtFileInput: $("#gtFileInput"),
  gtFileName: $("#gtFileName"),
  clearGtBtn: $("#clearGtBtn"),

  // Progress
  progressBlock:      $("#progressBlock"),
  progressFill:       $("#progressFill"),
  progressPct:        $("#progressPct"),
  progressBar:        $("#progressBar"),
  progressStatusText: $("#progressStatusText"),
  progressEta:        $("#progressEta"),
  progressCurrentFile:$("#progressCurrentFile"),
  progressItemCount:  $("#progressItemCount"),

  // Results
  resultsCard:     $("#resultsCard"),
  gallery:         $("#gallery"),
  downloadAllBtn:  $("#downloadAllBtn"),
  clearResultsBtn: $("#clearResultsBtn"),

  // Metrics
  metricTotal:      $("#metricTotal"),
  metricAvgLatency: $("#metricAvgLatency"),
  metricCached:     $("#metricCached"),
  metricErrors:     $("#metricErrors"),
  metricMinLat:     $("#metricMinLat"),
  metricMaxLat:     $("#metricMaxLat"),
  metricThroughput: $("#metricThroughput"),
  metricTotalTime:  $("#metricTotalTime"),

  // Compare
  compareDropZone:       $("#compareDropZone"),
  compareFileInput:      $("#compareFileInput"),
  compareFileName:       $("#compareFileName"),
  compareRunBtn:         $("#compareRunBtn"),
  compareCancelBtn:      $("#compareCancelBtn"),
  compareCmap:           $("#compareCmap"),
  compareDevice:         $("#compareDevice"),
  compareEngine:         $("#compareEngine"),
  compareIncludeLarge:   $("#compareIncludeLarge"),
  compareResults:        $("#compareResults"),
  compareProgressBlock:  $("#compareProgressBlock"),
  compareProgressFill:   $("#compareProgressFill"),
  compareProgressPct:    $("#compareProgressPct"),
  compareProgressText:   $("#compareProgressText"),
  compareProgressEta:    $("#compareProgressEta"),
  compareChartCard:      $("#compareChartCard"),
  compareChartBody:      $("#compareChartBody"),
  compareChartToggle:    $("#compareChartToggle"),
  compareMetricSelect:   $("#compareMetricSelect"),
  compareMetricGrid:     $("#compareMetricGrid"),

  // Benchmark
  benchmarkModel:      $("#benchmarkModel"),
  benchmarkDevice:     $("#benchmarkDevice"),
  benchmarkEngine:     $("#benchmarkEngine"),
  benchmarkRunBtn:     $("#benchmarkRunBtn"),
  benchTorchLatency:   $("#benchTorchLatency"),
  benchOnnxLatency:    $("#benchOnnxLatency"),
  benchSpeedup:        $("#benchSpeedup"),
  benchRecommendedEngine: $("#benchRecommendedEngine"),
  benchRecommendationReason: $("#benchRecommendationReason"),
  benchThroughput:     $("#benchThroughput"),
  benchMemory:         $("#benchMemory"),
  benchProvider:       $("#benchProvider"),
  benchStatus:         $("#benchStatus"),
  performanceSubnav:   $$("[data-performance-view]"),
  performanceViewBenchmark: $("#performanceViewBenchmark"),
  performanceViewObservability: $("#performanceViewObservability"),
  observabilityRefreshBtn: $("#observabilityRefreshBtn"),
  observabilityExportBtn: $("#observabilityExportBtn"),
  observabilityCopyMetricsBtn: $("#observabilityCopyMetricsBtn"),
  observabilityTotalRequests: $("#observabilityTotalRequests"),
  observabilityHttpP95: $("#observabilityHttpP95"),
  observabilityInferenceRuns: $("#observabilityInferenceRuns"),
  observabilityInferenceP95: $("#observabilityInferenceP95"),
  observabilityCacheHitRatio: $("#observabilityCacheHitRatio"),
  observabilityCrashCount: $("#observabilityCrashCount"),
  observabilityTraceBody: $("#observabilityTraceBody"),
  observabilityBenchmarkBody: $("#observabilityBenchmarkBody"),
  observabilityCrashBody: $("#observabilityCrashBody"),
  observabilityUpdatedAt: $("#observabilityUpdatedAt"),
  observabilityStatus: $("#observabilityStatus"),
  observabilityChart: $("#observabilityChart"),

  // Experiments
  experimentName:         $("#experimentName"),
  experimentRunBtn:       $("#experimentRunBtn"),
  experimentExportJsonBtn:$("#experimentExportJsonBtn"),
  experimentExportCsvBtn: $("#experimentExportCsvBtn"),
  experimentStatus:       $("#experimentStatus"),
  experimentCount:        $("#experimentCount"),
  experimentAvgLatency:   $("#experimentAvgLatency"),
  experimentBestAbsRel:   $("#experimentBestAbsRel"),
  experimentStatusMetric: $("#experimentStatusMetric"),
  experimentTableBody:    $("#experimentTableBody"),
  experimentPreviews:     $("#experimentPreviews"),

  // Lightbox
  lightboxBackdrop: $("#lightboxBackdrop"),
  lightboxClose:    $("#lightboxClose"),
  lbOrigImg:        $("#lbOrigImg"),
  lbDepthImg:       $("#lbDepthImg"),
  lightboxMetrics:  $("#lightboxMetrics"),
  lbSlider:         $("#lbSlider"),
  lbRangeValue:     $("#lbRangeValue"),
  lbTags:           $("#lbTags"),
  lbDlDepth:        $("#lbDlDepth"),
  lbDlGray:         $("#lbDlGray"),

  // Webcam
  webcamStatusPill:       $("#webcamStatusPill"),
  webcamStartBtn:         $("#webcamStartBtn"),
  webcamStopBtn:          $("#webcamStopBtn"),
  webcamPauseBtn:         $("#webcamPauseBtn"),
  webcamCaptureBtn:       $("#webcamCaptureBtn"),
  webcamTargetFps:        $("#webcamTargetFps"),
  webcamMaxDim:           $("#webcamMaxDim"),
  webcamSmoothing:        $("#webcamSmoothing"),
  webcamVideo:            $("#webcamVideo"),
  webcamCaptureCanvas:    $("#webcamCaptureCanvas"),
  webcamDepthImg:         $("#webcamDepthImg"),
  webcamDepthPlaceholder: $("#webcamDepthPlaceholder"),
  webcamCameraState:      $("#webcamCameraState"),
  webcamInferenceState:   $("#webcamInferenceState"),
  webcamTargetFpsMetric:  $("#webcamTargetFpsMetric"),
  webcamEffectiveFps:     $("#webcamEffectiveFps"),
  webcamBackendLatency:   $("#webcamBackendLatency"),
  webcamEndToEndLatency:  $("#webcamEndToEndLatency"),
  webcamProcessedFrames:  $("#webcamProcessedFrames"),
  webcamSkippedFrames:    $("#webcamSkippedFrames"),
  webcamErrorCount:       $("#webcamErrorCount"),
  webcamActiveModel:      $("#webcamActiveModel"),
  webcamActiveDevice:     $("#webcamActiveDevice"),
  webcamActiveColormap:   $("#webcamActiveColormap"),
  webcamLog:              $("#webcamLog"),


  // 3D Reconstruction
  reconstructStatusPill:       $("#reconstructStatusPill"),
  reconstructDropZone:         $("#reconstructDropZone"),
  reconstructFileInput:        $("#reconstructFileInput"),
  reconstructInputPreview:     $("#reconstructInputPreview"),
  reconstructFileName:         $("#reconstructFileName"),
  reconstructBrowseBtn:        $("#reconstructBrowseBtn"),
  reconstructUseLatestBtn:     $("#reconstructUseLatestBtn"),
  reconstructClearBtn:         $("#reconstructClearBtn"),
  reconstructOpenCaptureBtn:   $("#reconstructOpenCaptureBtn"),
  reconstructCaptureStatus:    $("#reconstructCaptureStatus"),
  captureBackdrop:             $("#captureBackdrop"),
  captureCloseBtn:             $("#captureCloseBtn"),
  captureVideo:                $("#captureVideo"),
  captureCanvas:               $("#captureCanvas"),
  captureStillBtn:             $("#captureStillBtn"),
  captureDetections:           $("#captureDetections"),
  captureModalStatus:          $("#captureModalStatus"),
  capturePlaceholder:          $("#capturePlaceholder"),
  reconstructFormat:           $("#reconstructFormat"),
  reconstructMaxDim:           $("#reconstructMaxDim"),
  reconstructMaxPoints:        $("#reconstructMaxPoints"),
  reconstructPreviewPoints:    $("#reconstructPreviewPoints"),
  reconstructSampling:         $("#reconstructSampling"),
  reconstructCoordinateSystem: $("#reconstructCoordinateSystem"),
  reconstructIncludeRgb:       $("#reconstructIncludeRgb"),
  reconstructFocalScale:       $("#reconstructFocalScale"),
  reconstructDepthScale:       $("#reconstructDepthScale"),
  reconstructNearPct:          $("#reconstructNearPct"),
  reconstructFarPct:           $("#reconstructFarPct"),
  reconstructRunBtn:           $("#reconstructRunBtn"),
  reconstructCancelBtn:        $("#reconstructCancelBtn"),
  reconstructProgressBlock:    $("#reconstructProgressBlock"),
  reconstructProgressFill:     $("#reconstructProgressFill"),
  reconstructProgressPct:      $("#reconstructProgressPct"),
  reconstructProgressText:     $("#reconstructProgressText"),
  reconstructProgressEta:      $("#reconstructProgressEta"),
  pointCloudCanvas:            $("#pointCloudCanvas"),
  pointCloudPlaceholder:       $("#pointCloudPlaceholder"),
  pointCloudModeMessage:       $("#pointCloudModeMessage"),
  pointCloudResetViewBtn:      $("#pointCloudResetViewBtn"),
  pointCloudPointSize:         $("#pointCloudPointSize"),
  pointCloudAutoRotate:        $("#pointCloudAutoRotate"),
  reconstructPointCount:       $("#reconstructPointCount"),
  reconstructPreviewCount:     $("#reconstructPreviewCount"),
  reconstructArtifactSize:     $("#reconstructArtifactSize"),
  reconstructLatency:          $("#reconstructLatency"),
  reconstructModel:            $("#reconstructModel"),
  reconstructDevice:           $("#reconstructDevice"),
  reconstructEngine:           $("#reconstructEngine"),
  reconstructResolution:       $("#reconstructResolution"),
  reconstructBounds:           $("#reconstructBounds"),
  reconstructWarnings:         $("#reconstructWarnings"),
  reconstructDepthCached:      $("#reconstructDepthCached"),
  reconstructFormatLabel:      $("#reconstructFormatLabel"),
  reconstructDepthPreview:     $("#reconstructDepthPreview"),
  reconstructDepthEmpty:       $("#reconstructDepthEmpty"),
  reconstructDownloadDepthBtn: $("#reconstructDownloadDepthBtn"),
  reconstructDownloadBtn:      $("#reconstructDownloadBtn"),
  reconstructCopyMetaBtn:      $("#reconstructCopyMetaBtn"),
  reconstructDownloadMetaBtn:  $("#reconstructDownloadMetaBtn"),

  toastContainer: $("#toastContainer"),
  bgCanvas:       $("#bgCanvas"),
};
